# Generated by Django 2.2.19 on 2022-11-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='Ingredients',
        ),
    ]
