# Generated by Django 2.2.19 on 2022-12-01 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20221124_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(db_index=True, through='recipe.TagsRecipes', to='recipe.Tags', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Описание'),
        ),
    ]
